# Sources:
# https://github.com/replicatedhq/outdated/blob/v0.4.0/.github/workflows/build.yaml

name: build-and-test

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - "*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout/releases
      - uses: actions/checkout@v1
      - name: Build and test
        run: make
